Part15/Models/ErrorViewModel.cs
using System;

namespace Part15.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Part15/Components/TimerViewComponent.cs
using Microsoft.AspNetCore.Html;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Part15.Components
{
    // Есть три способа определения компонента:
    // 1. Определение компонента как обычного класса(класс POCO)
    // 2. Наследование от базового класса ViewComponent
    // 3. Применение к классу атрибута[ViewComponent]
    public class Time : ViewComponent
    {
        // ContentViewComponentResult: применяется для отправки текстового контента. Для создания объекта используется метод Content()
        public IViewComponentResult Invoke()
        {
            return Content(DateTime.Now.ToString("hh:mm:ss"));
        }
    }
    public class TimeBold : ViewComponent
    {
        // HtmlContentViewComponentResult: представляет фрагмент кода HTML, который инкорпорируется в веб-станицу
        // для генерации html-фрагментов, которые вставляются в основное представление, применяется класс HtmlContentViewComponentResult
        public IViewComponentResult Invoke()
        {
            return new HtmlContentViewComponentResult(new HtmlString($"<b>Текущее вермя {DateTime.Now.ToString("hh:mm:ss")}</b>"));
        }
    }
    public class GetSecondsViewComponent
    {
        public string Invoke(int delay)
        {
            return (DateTime.Now.Second + delay).ToString();
        }
    }

    [ViewComponent]
    public class Today
    {
        public string Invoke()
        {
            return DateTime.Now.ToString("dd.hh.yy");
        }
    }

    // ViewViewComponentResult: используется для генерации представления Razor с возможностью передачи модели.
    // Для создания этого объекта может применяться метод View() класса ViewComponent
    public class UsersList : ViewComponent
    {
        List<string> users;
        public UsersList()
        {
            users = new List<string>()
            {
                "Tom", "Bob", "Ivan"
            };
        }
        public IViewComponentResult Invoke()
        {
            return View(users);
        }
    }

    public class NewUsersList : ViewComponent
    {
        List<string> users;
        public NewUsersList()
        {
            users = new List<string>()
            {
                "Tom", "Bob", "Ivan"
            };
        }
        public IViewComponentResult Invoke()
        {
            int number = users.Count();
            if (Request.Query.ContainsKey("number"))
            {
                Int32.TryParse(Request.Query["number"].ToString(), out number);
            }
            ViewBag.Users = users.Take(number);
            ViewData["Header"] = $"Количество = {users.Count}";
            return View();
        }
    }

    // Иногда возникает необходимость в компоненте выполнить некоторую асинхронную операцию,
    // например, для обращения к базе данных, к внешнему сетевому ресурсу, чтению файла и т.д.
    public class Header : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            string htmlContent = String.Empty;
            using (StreamReader reader = new StreamReader("Files/header.html"))
            {
                htmlContent = await reader.ReadToEndAsync();
            }
            return new HtmlContentViewComponentResult(new HtmlString(htmlContent));
        }
    }
}

Part15/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Part15.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Part15.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Part15/Views/Home/Components/NewUsersList/Default.cshtml
<h3>@ViewData["Header"]</h3>
<ul>
    @foreach (var user in ViewBag.Users)
    {
        <li>@user</li>
    }
</ul>

Part15/Views/Home/Components/UsersList/Default.cshtml
@model IEnumerable<string>
<h4>Список пользователей</h4>
<ul>
    @foreach (var user in Model)
    {
        <li>@user</li>
    }
</ul>

Part15/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@*View Component состоит из двух частей: класса на C# и частичного представления, которое вызывает методы этого класса.*@
<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

@*использование компонента*@
@await Component.InvokeAsync("Today")
@await Component.InvokeAsync("Time")
@await Component.InvokeAsync("TimeBold")
<br>
@*Для передачи значений параметрам метода Invoke/InvokeAsync в методе Component.InvokeAsync() в качестве
    второго аргумента указывается анонимный объект, который устанавливает значения всех параметров*@
@await Component.InvokeAsync("GetSeconds", new { delay = 2 })
@await Component.InvokeAsync("Header")

Part15/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Part15</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Part15</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Part15 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>